[package]
name = "usage_tracking"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[package.metadata.cargo-machete]
ignored = []

[lib]
doctest = false

[features]
testing = [
    "common/testing",
    "events/testing",
    "metrics/testing",
    "proptest",
    "proptest-derive",
    "value/testing",
]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
common = { workspace = true }
events = { workspace = true }
headers = { workspace = true }
metrics = { workspace = true }
parking_lot = { workspace = true, features = ["hardware-lock-elision"] }
pb = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
tracing = { workspace = true }
value = { workspace = true }

[dev-dependencies]
cmd_util = { workspace = true }
common = { workspace = true, features = ["testing"] }
events = { workspace = true, features = ["testing"] }
metrics = { workspace = true, features = ["testing"] }
proptest = { workspace = true }
proptest-derive = { workspace = true }
value = { workspace = true, features = ["testing"] }

[lints]
workspace = true
