[package]
name = "interval_map"
version = "0.1.0"
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[dependencies]
common = { workspace = true }
fastrand = { workspace = true }
slab = { workspace = true }

[dev-dependencies]
cmd_util = { workspace = true }
common = { workspace = true, features = ["testing"] }
divan = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
tikv-jemallocator = { workspace = true }

[[bench]]
name = "bench"
harness = false

[lints]
workspace = true
