# Netlify Build Configuration for Convex Docs (Rush Monorepo)
[build]
  # Build from repository root to support workspace:* dependencies
  base = "."

  # Use pnpm to support workspace:* protocol
  # Install and build dependencies using pnpm filter
  command = """
    corepack enable && \
    corepack prepare pnpm@latest --activate && \
    pnpm install --frozen-lockfile=false && \
    pnpm --filter convex... run build && \
    pnpm --filter convex-ai-chat... run build && \
    pnpm --filter convex-analytics... run build && \
    pnpm --filter docs run build
  """

  # Publish directory - absolute path from repo root
  publish = "npm-packages/docs/build"

# Node version
[build.environment]
  NODE_VERSION = "20.19.5"

# Headers configuration for font caching
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, stale-while-revalidate=86400"

# SPA redirect configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
