[package]
name = "search"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[features]
testing = [
    "common/testing",
    "errors/testing",
    "indexing/testing",
    "metrics/testing",
    "proptest",
    "proptest-derive",
    "storage/testing",
    "text_search/testing",
    "value/testing",
    "vector/testing",
]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
async_lru = { workspace = true }
async_zip_0_0_9 = { workspace = true }
bitvec = { workspace = true }
bytes = { workspace = true }
bytesize = { workspace = true }
cmd_util = { workspace = true }
common = { workspace = true }
compact_str = { workspace = true }
errors = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }
imbl = { workspace = true }
imbl_slab = { workspace = true }
indexing = { workspace = true }
itertools = { workspace = true }
levenshtein_automata = { workspace = true }
maplit = { workspace = true }
metrics = { workspace = true }
pb = { workspace = true }
prometheus = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
qdrant_segment = { workspace = true }
rand = { workspace = true }
ref-cast = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
storage = { workspace = true }
strum = { workspace = true }
sucds = { workspace = true }
tantivy = { workspace = true }
tantivy-common = { workspace = true }
tempfile = { workspace = true }
text_search = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
value = { workspace = true }
vector = { workspace = true }
walkdir = { workspace = true }
xorf = { workspace = true }

[dev-dependencies]
common = { workspace = true, features = ["testing"] }
convex_macro = { workspace = true }
divan = { workspace = true }
errors = { workspace = true, features = ["testing"] }
indexing = { workspace = true, features = ["testing"] }
metrics = { workspace = true, features = ["testing"] }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }
runtime = { workspace = true, features = ["testing"] }
storage = { workspace = true, features = ["testing"] }
text_search = { workspace = true, features = ["testing"] }
value = { workspace = true, features = ["testing"] }
vector = { workspace = true, features = ["testing"] }

[[bench]]
name = "memory_index"
harness = false

[lints]
workspace = true
