[package]
name = "simulation"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[package.metadata.cargo-udeps.ignore]
normal = [
    "anyhow",
    "application",
    "common",
    "deno_core",
    "errors",
    "futures",
    "isolate",
    "keybroker",
    "maplit",
    "model",
    "rand",
    "rand_chacha",
    "serde",
    "serde_json",
    "sync",
    "sync_types",
    "tokio",
    "tracing",
]
development = [
    "anyhow",
    "application",
    "common",
    "deno_core",
    "errors",
    "futures",
    "isolate",
    "keybroker",
    "maplit",
    "model",
    "rand",
    "rand_chacha",
    "serde",
    "serde_json",
    "sync",
    "sync_types",
    "tokio",
    "tracing",
]

[lib]
doctest = false

[features]
testing = [
    "application/testing",
    "common/testing",
    "errors/testing",
    "isolate/testing",
    "keybroker/testing",
    "metrics/testing",
    "model/testing",
    "sync/testing",
    "proptest",
    "proptest-derive",
]

[dependencies]
anyhow = { workspace = true }
application = { workspace = true }
common = { workspace = true }
deno_core = { workspace = true }
errors = { workspace = true }
futures = { workspace = true }
isolate = { workspace = true }
keybroker = { workspace = true }
maplit = { workspace = true }
model = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sync = { workspace = true }
sync_types = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
application = { workspace = true, features = ["testing"] }
common = { workspace = true, features = ["testing"] }
convex = { workspace = true, features = ["testing"] }
convex_macro = { workspace = true }
errors = { workspace = true, features = ["testing"] }
isolate = { workspace = true, features = ["testing"] }
keybroker = { workspace = true, features = ["testing"] }
metrics = { workspace = true, features = ["testing"] }
model = { workspace = true, features = ["testing"] }
must-let = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand_distr = { workspace = true }
runtime = { workspace = true, features = ["testing"] }
sync = { workspace = true, features = ["testing"] }
uuid = { workspace = true }

[lints]
workspace = true
