[package]
name = "runtime"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[features]
testing = ["common/testing", "metrics/testing"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
common = { workspace = true }
futures = { workspace = true }
metrics = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
tokio-metrics-collector = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
common = { workspace = true, features = ["testing"] }
metrics = { workspace = true, features = ["testing"] }

[lints]
workspace = true
