[package]
name = "isolate"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

build = "build.rs"
include = ["data"]

[package.metadata.cargo-udeps.ignore]
normal = ["mysql"]
development = ["mysql"]

[package.metadata.cargo-machete]
ignored = ["phf"]

[lib]
doctest = false

[features]
testing = [
    "common/testing",
    "database/testing",
    "errors/testing",
    "keybroker/testing",
    "maplit",
    "metrics/testing",
    "model/testing",
    "must-let",
    "proptest",
    "proptest-derive",
    "proptest-http",
    "runtime/testing",
    "search/testing",
    "storage/testing",
    "usage_tracking/testing",
    "value/testing",
    "vector/testing",
    "udf/testing",
]
tracy-tracing = ["common/tracy-tracing"]

[dependencies]
anyhow = { workspace = true }
async-broadcast = { workspace = true }
async-channel = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
aws-lc-rs = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
cmd_util = { workspace = true }
common = { workspace = true }
const-oid = { workspace = true }
convex_macro = { workspace = true }
database = { workspace = true }
deno_core = { workspace = true }
deno_core_icudata = { workspace = true }
derive_more = { workspace = true }
elliptic-curve = { workspace = true }
encoding_rs = { workspace = true }
errors = { workspace = true }
fastrace = { workspace = true }
file_storage = { workspace = true }
futures = { workspace = true }
headers = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
humansize = { workspace = true }
itertools = { workspace = true }
keybroker = { workspace = true }
maplit = { workspace = true, optional = true }
metrics = { workspace = true }
mime = { workspace = true }
model = { workspace = true }
multer = { workspace = true }
must-let = { workspace = true, optional = true }
openssl = { workspace = true }
p256 = { workspace = true }
p384 = { workspace = true }
parking_lot = { workspace = true }
pb = { workspace = true }
phf = { workspace = true }
pkcs1 = "0.7.5"
pkcs8 = "0.10.2"
prometheus = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
proptest-http = { workspace = true, optional = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
regex = { workspace = true }
runtime = { workspace = true }
search = { workspace = true }
semver = { workspace = true }
sentry = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
sourcemap = { workspace = true }
spki = { workspace = true }
storage = { workspace = true }
sync_types = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
udf = { workspace = true }
url = { workspace = true }
usage_tracking = { workspace = true }
uuid = { workspace = true }
value = { workspace = true }
vector = { workspace = true }

[target."cfg(not(windows))".dependencies]
libc = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
async-broadcast = { workspace = true }
async-channel = { workspace = true }
common = { workspace = true, features = ["testing"] }
database = { workspace = true, features = ["testing"] }
divan = { workspace = true }
errors = { workspace = true, features = ["testing"] }
hyper = { workspace = true }
keybroker = { workspace = true, features = ["testing"] }
maplit = { workspace = true }
metrics = { workspace = true, features = ["testing"] }
model = { workspace = true, features = ["testing"] }
must-let = { workspace = true }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
proptest-http = { workspace = true }
runtime = { workspace = true, features = ["testing"] }
search = { workspace = true, features = ["testing"] }
shape_inference = { workspace = true, features = ["testing"] }
storage = { workspace = true, features = ["testing"] }
udf = { workspace = true, features = ["testing"] }
usage_tracking = { workspace = true, features = ["testing"] }
value = { workspace = true, features = ["testing"] }
vector = { workspace = true, features = ["testing"] }

[[bench]]
name = "new_context"
harness = false

[lints]
workspace = true
