[project]
name = "text-importer"
version = "0.1.0"
description = "Vector importer script"
authors = [{ name = "Convex, Inc.", email = "no-reply@convex.dev" }]
requires-python = "~=3.13.0"
dependencies = [
    "python-dotenv>=1.0.0,<2",
    "convex>=0.6.0,<0.7",
]

[project.scripts]
main = "main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "main.py" }]
