[package]
name = "json_trait"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
errors = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
