[package]
name = "workos_client"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[features]
testing = ["common/testing", "errors/testing"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
common = { workspace = true }
errors = { workspace = true }
http = { workspace = true }
oauth2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
common = { workspace = true, features = ["testing"] }
errors = { workspace = true, features = ["testing"] }

[lints]
workspace = true
