[package]
name = "packed_value"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[features]
testing = ["proptest", "value/testing"]

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
flexbuffers = { workspace = true }
proptest = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
value = { workspace = true }

[dev-dependencies]
cmd_util = { workspace = true }
criterion = { workspace = true }
maplit = { workspace = true }
proptest = { workspace = true }
value = { workspace = true, features = ["testing"] }

[[bench]]
name = "packed_value"
harness = false

[lints]
workspace = true
