[env]
CARGO_WORKSPACE_ROOT = { value = "", relative = true }
CHRONO_TZ_TIMEZONE_FILTER = "US/Pacific"
# HACK: use custom build with leaptiering off,
# until either https://issues.chromium.org/issues/419147069 is fixed or we can
# turn on pointer compression
RUSTY_V8_MIRROR = "https://github.com/get-convex/rusty_v8/releases/download"

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=neoverse-n1", "-Cforce-frame-pointers=yes"]

[target.aarch64-apple-darwin]
rustflags = ["-Ctarget-cpu=apple-m1"]

[target.x86_64-pc-windows-msvc]
# FORCE:MULTIPLE is a bit sketchy. v8 and rocksdb both export the same symbol.
# This seems to work around it to build on windows, but it's not ideal.
rustflags = ["-Clink-arg=/FORCE:MULTIPLE", "-Clink-arg=/STACK:4194304"]

[target.'cfg(all())']
rustflags = ["--cfg", "tokio_unstable"]

[net]
git-fetch-with-cli = true
