[package]
name = "indexing"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[features]
testing = [
    "common/testing",
    "errors/testing",
    "metrics/testing",
    "runtime/testing",
    "value/testing",
]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
common = { workspace = true }
derive_more = { workspace = true }
errors = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }
imbl = { workspace = true }
itertools = { workspace = true }
metrics = { workspace = true }
tracing = { workspace = true }
value = { workspace = true }

[dev-dependencies]
common = { workspace = true, features = ["testing"] }
convex_macro = { workspace = true }
divan = { workspace = true }
errors = { workspace = true, features = ["testing"] }
maplit = { workspace = true }
metrics = { workspace = true, features = ["testing"] }
must-let = { workspace = true }
runtime = { workspace = true, features = ["testing"] }
value = { workspace = true, features = ["testing"] }

[[bench]]
name = "index_registry"
harness = false

[lints]
workspace = true
