[package]
name = "keybroker"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[features]
testing = [
    "common/testing",
    "errors/testing",
    "metrics/testing",
    "rsa",
    "runtime/testing",
]

[dependencies]
anyhow = { workspace = true }
aws-lc-rs = { workspace = true }
biscuit = { workspace = true }
byteorder = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
cmd_util = { workspace = true }
common = { workspace = true }
derive_more = { workspace = true }
errors = { workspace = true }
hex = { workspace = true }
metrics = { workspace = true }
openidconnect = { workspace = true }
pb = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
rsa = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sodium_secretbox = { workspace = true }
sync_types = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
common = { workspace = true, features = ["testing"] }
errors = { workspace = true, features = ["testing"] }
metrics = { workspace = true, features = ["testing"] }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rsa = { workspace = true }
runtime = { workspace = true, features = ["testing"] }

[lints]
workspace = true
