[package]
name = "pb_build"
version = "0.1.0"
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[package.metadata.cargo-machete]
ignored = ["cfg_if", "tonic_build"]

[lib]
doctest = false

[dependencies]
cfg-if = { workspace = true }
prost = { workspace = true }
tonic-build = { workspace = true }

[lints]
workspace = true
